Handlebars:
  beautifiers:
    - JS-Beautify
  indent_style: 'space'
  indent_size: 2
  brace_style: 'collapse'
  indent_inner_html: true
  indent_scripts: 'normal'
  newline_before_tags: [ 'head', 'body' ]
  quotes: 'double'
  wrap_attributes: 'force-aligned'
  wrap_attributes_indent_size: 2
  wrap_line_length: 80
